#spring:
#  autoconfigure:
#    #自动化配置 例外处理
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#  datasource:
#    dynamic:
#      #默认这里选择默认数据
#      primary: mysql
#      strict: true
#      datasource:
#        #可以配置多个
#        mysql:
#          url: jdbc:mysql://localhost:3306/dbName?autoReconnect=true&allowPublicKeyRetrieval=True&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          druid:
#            initial-size: 5 #连接池初始化大小
#            min-idle: 10 #最小空闲连接数
#            max-active: 20 #最大连接数
#            filters: stat,slf4j,wall
#            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#            # 合并多个DruidDataSource的监控数据
#            use-global-data-source-Stat: true
#            validationQuery: SELECT 'x'
#            testWhileIdle: true
#            test-on-borrow: false
#            test-on-return: false
#        clickhouse:
#          url: jdbc:clickhouse://localhost:8123/dbName
#          #          username:
#          #          password:
#          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
#          druid:
#            initial-size: 5 #连接池初始化大小
#            min-idle: 10 #最小空闲连接数
#            max-active: 20 #最大连接数
#            filters: stat,log4j2,wall
#            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#            # 合并多个DruidDataSource的监控数据
#            use-global-data-source-Stat: true
#            validationQuery: SELECT 'x'
#            testWhileIdle: true
#            test-on-borrow: false
#            test-on-return: false
#
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        enabled: true
#        login-username: druid
#        login-password: druid