#mx:
#  #安全模块配置
#  security:
#    #客户端名称 默认default
#    client:
#    #登录前后处理实现类
#    login-handler-class:
#    #用户操作前后处理实现类
#    user-handler-class:
#    #是否执行跨域
#    cross: true
#    #验证错误N次后锁定账户  默认不锁定  0不锁定
#    error-count:
#
#sa-token:
#  # token名称 (同时也是cookie名称)
#  token-name: mxToken
#  # token有效期，单位s 默认30天, -1代表永不过期
#  timeout: 2592000
#  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
#  activity-timeout: -1
#  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
#  is-concurrent: true
#  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
#  is-share: true
#  # token风格
#  token-style: uuid
#  # 是否输出操作日志
#  is-log: false
#  #打印banner
#  is-print: false
#
