#mybatis-plus:
#  global-config:
#    banner: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#  type-aliases-package: com.mx.dao.mapper
#  mapper-locations: classpath*:mybatis/mapper/*.xml
#
