#mybatis-plus:
#  global-config:
#    banner: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#  type-aliases-package: com.mx.dao.mapper
#  mapper-locations: classpath*:mybatis/mapper/*.xml
#
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/dbName?autoReconnect=true&allowPublicKeyRetrieval=True&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
#      filters: stat,wall,log4j2
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        enabled: true
#        login-username: druid
#        login-password: druid
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      # 合并多个DruidDataSource的监控数据
#      use-global-data-source-Stat: true
#      validationQuery: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false